### ISSUE TITLE
Setting Number Device class?

### ISSUE THREAD

**Issue by lovekull76** [alexbarcelo/hass-mqtt-things#2]
Hi,

Just love your work on this and I use it for many things!
But I would love to be able to add device_class and unit_of_measurement for numbers as well, can you make it happen? Please!

Best regards, L

**Comment by alexbarcelo** [comment]
Commit c363dfc includes `device_class` and `unit_of_measurement`. Soon v0.5.6 will be published with those changes.

I wondered if it was better to do some cleanup and check other attributes (which may be easy to add) in order to poublish a more comprehensive new version... but I am unable to allocate time for that now. I hope that v0.6.0 will address all those missing attributes for this and other integrations.
