### ISSUE TITLE
`add_thing(my_thing, origin=DeviceInfo())` doesnt work.

### ISSUE THREAD

**Issue by cameroncros** [alexbarcelo/hass-mqtt-things#3]
DeviceInfo results in a dict, which is not hashable, and therefore cannot be used as a key for the `things` dict.

None works fine, so the examples are all okay. I dont think I am using it incorrectly, but it doesnt seem to work.

Nice library otherwise, its almost exactly what I want. I may create a PR if I can find a nice easy fix.

**Comment by alexbarcelo** [comment]
You are right, I completely messed it up. Quickest fix is to change a little bit and have a flat list of pairs `(DeviceInfo, Thing)` instead of the dictionary  hierarchical approach.

My tests suggest that now (i.e. v0.5.9 I just pushed) is working, and the interface of `add_thing` should be unchanged. Feel free to comment and reopen this issue if that's not the case.
